### PR TITLE
Use 204 on empty delete response

### PR DESCRIPTION
**Pull request by medokin**
See: http://jsonapi.org/format/#crud-deleting

### CODE REVIEW

**Comment by medokin** [comment]
No idea why the test is failing

**Comment by jaredcnance** [comment]
@medokin thanks for the PR! I'll dig into it this afternoon.

**Comment by jaredcnance** [comment]
the test you updated was intended to verify that the server returns a 404 if a `DELETE` request is received for an entity that doesn't exist. I've updated the appropriate tests.

Currently, the organization of the tests is less than desirable and I hope to change that in the near future

**Comment by medokin** [comment]
Perfect, thanks. It works fine now. Would be easier to contribute if #47 was finished.

**Comment by jaredcnance** [comment]
#51 is open to resolve #47. However, it looks like AppVeyor has yet to upgrade their version of the SDK. Once that is fixed, I'll merge into master. Until then, if you'd like to contribute, you can work off the `develop` branch

**Pull request merged**
